import type { Metadata } from 'next';
import '@/app/globals.css';
import { redirect } from 'next/navigation';
import { auth } from '@/lib/auth';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  if (!session?.accessToken) {
    redirect('/login');
  }
  return <div>{children}</div>;
}
